# fly.toml app configuration file generated for bioss-api on 2025-06-01T23:30:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bioss-api'
primary_region = 'ams'

[build]
  dockerfile = '/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
